version: '3'

services:
  backend:
    container_name: "dev-backend"
    build:
      context: ./Restart_Project
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./Restart_Project/Restart:/Restart
    command: python3 /Restart/manage.py runserver 0.0.0.0:8000  --insecure
    ports:
      - "8000:8000"
    tty: true
  app:
    container_name: "dev-app"
    build:
      context: ./frontend_Project
      dockerfile: docker/node/Dockerfile.dev
    volumes:
      - ./frontend_Project/webpack-babel-react-env:/app
      - front_node_modules:/app/node_modules
      # /app/buildをバインドマウントする際
      # (開発時は検証しやすい様に主にコンテナ内に作成する様にする)
      #- front_build:/app/build
    command: sh -c "cd /app && npm run start && tail -f /dev/null"
    ports:
      - "3000:3000"

volumes:
  front_node_modules:
#  front_build:
